version: '2'

services:
    php:
        build: './php-fpm'
        environment: 
            SYMFONY_ENV: 'dev'
        volumes: 
            - './symfony:/var/www:cached'
    nginx:
        build: './nginx'
        ports:
            - '1337:80'
        volumes_from: 
            - 'php'
